In [3]:
import numpy as np

In [2]:
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]


In [7]:
#（5）或者(5,)
zeros = np.zeros((5))
print(zeros)

[0. 0. 0. 0. 0.]


In [6]:
ones = np.ones((5))
print(ones)

[1. 1. 1. 1. 1.]


In [11]:
randoms = np.random.random((5))
print(randoms)

[0.91736286 0.7523737  0.87871812 0.15088771 0.49442294]


In [10]:
#二维数组，长度为5
zeros = np.zeros((2, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


![](https://www.numpy.org.cn/static/images/article/numpy_2D_slicing_diagram-1.jpg)