In [3]:
import numpy as np

In [2]:
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]


In [7]:
#（5）或者(5,)
zeros = np.zeros((5))
print(zeros)

[0. 0. 0. 0. 0.]


In [6]:
ones = np.ones((5))
print(ones)

[1. 1. 1. 1. 1.]


In [11]:
randoms = np.random.random((5))
print(randoms)

[0.91736286 0.7523737  0.87871812 0.15088771 0.49442294]


In [10]:
#二维数组，2行5列
zeros = np.zeros((2, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
arange = np.arange(10)
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
reshape = arange.reshape((2,5))
print(reshape)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
linspace = np.linspace(0,10,num=4)
print(linspace)

[ 0.          3.33333333  6.66666667 10.        ]


In [18]:
empty = np.empty((2,3))
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
full = np.full((2,3), 8)
print(full)

[[8 8 8]
 [8 8 8]]


In [21]:
eye = np.eye(3,3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
m = np.array([[1,2,3],[4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [26]:
a = np.array([(1,2,3),(4,5,6)])
print(a)


[[1 2 3]
 [4 5 6]]


#多维数组切片
![](https://www.numpy.org.cn/static/images/article/numpy_2D_slicing_diagram-1.jpg)